name: Run Auto Sign 

on:
  workflow_dispatch:
  schedule:
    # Beijing time
    - cron: "0 6 * * *"
      timezone: "Asia/Shanghai"

env:
  SM_USERNAME: ${{ secrets.SM_USERNAME }}
  SM_PASSWORD: ${{ secrets.SM_PASSWORD }}
  SM_LOGIN: ${{ secrets.SM_LOGIN }}
  SM_USER_ID: ${{ secrets.SM_USER_ID }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        id: build
        run: |
          npm install
      - name: Run 
        id: run
        run: |
          node main.js 
